#!/bin/sh

# 你可能需要修改下这个路径
prefix='/home/www/OrmBuild'

arg=();

for((i=1;i<=$#;i++)); do
    var=$i
    pv="${!var}"
    prl=${#pv}
    prv=${pv:0:1}
    prc=${pv:1:$prl}

    if [ "$prv" = "-" ]; then
        pv='+'${prc}
    fi

    arg[i]=$pv
done

`which php` -f ${prefix}"/gorm.php" ${arg[*]}