#!/bin/sh

# 你可能需要修改下这个路径
prefix='/home/www/OrmBuild'

arg=();

for((i=1;i<=$#;i++)); do
    var=$i
    pv="${!var}"
    prl=${#pv}
    prv=${pv:1:1}
    prc=${pv:2:$prl}

    if [ "$prv" = "-" ]; then
        pv='+'${prc}
    fi

    arg[i]=$pv
done

/usr/local/bin/php -f ${prefix}"/gorm.php" ${arg[*]}
