#!/bin/sh

arg=();

for((i=1;i<=$#;i++)); do
    var=$i
    pv="${!var}"
    prl=`expr length "$pv"`
    prv=`expr substr "$pv" 1 1`
    prc=`expr substr "$pv" 2 "$prl"`

    if [ $prv = "-" ]; then
        pv='+'${prc}
    fi

    arg[i]=$pv
done

/usr/bin/php -f gorm.php ${arg[*]}